const expensiveRules = require('./expensive-rules');

/** @type { import('eslint').Linter.Config } */
module.exports = {
  plugins: ['import', 'simple-import-sort'],
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.mjs', '.js', '.json', '.jsx'],
      },
    },
    'import/core-modules': [],
    'import/ignore': ['node_modules', '\\.(coffee|scss|css|less|hbs|svg|json)$'],
  },
  rules: {
    'import/consistent-type-specifier-style': ['warn', 'prefer-top-level'],
    'import/default': expensiveRules('error'),
    'import/dynamic-import-chunkname': 'off',
    'import/export': expensiveRules('error'),
    'import/exports-last': 'off',
    'import/extensions': ['error', 'always', { js: 'never', jsx: 'never', ts: 'never', tsx: 'never' }],
    'import/first': 'error',
    'import/group-exports': 'off',
    'import/max-dependencies': ['off', { ignoreTypeImports: true }],
    'import/named': expensiveRules('error'),
    'import/namespace': expensiveRules('error'),
    'import/newline-after-import': 'warn',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'error',
    'import/no-anonymous-default-export': 'off',
    'import/no-commonjs': 'off',
    'import/no-cycle': expensiveRules(['error', { maxDepth: Infinity }]),
    'import/no-default-export': 'off',
    'import/no-deprecated': expensiveRules('warn'),
    'import/no-duplicates': 'error',
    'import/no-dynamic-require': 'off',
    'import/no-empty-named-blocks': 'error',
    'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
    'import/no-import-module-exports': 'off',
    'import/no-internal-modules': 'off',
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': expensiveRules('error'),
    'import/no-named-default': 'error',
    'import/no-named-export': 'off',
    'import/no-namespace': 'off',
    'import/no-nodejs-modules': 'off',
    'import/no-relative-packages': 'error',
    'import/no-relative-parent-imports': 'off',
    'import/no-restricted-paths': 'off',
    'import/no-self-import': 'error',
    'import/no-unassigned-import': 'off',
    'import/no-unresolved': ['error', { caseSensitiveStrict: true }],
    'import/no-unused-modules': 'off',
    'import/no-useless-path-segments': 'warn',
    'import/no-webpack-loader-syntax': 'error',
    'import/order': ['off', { groups: ['builtin', ['external', 'internal'], 'parent', ['sibling', 'index']] }], // collision
    'import/prefer-default-export': 'off',
    'import/unambiguous': 'off',
    'simple-import-sort/exports': 'warn',
    'simple-import-sort/imports': 'warn',
    'sort-imports': 'off',
  },
};
