import plugin from 'eslint-plugin-playwright';

import { globs } from '../utils/globs.mjs';

/** @return { import('eslint').Linter.Config } */
function playwright() {
  return {
    plugins: { playwright: plugin },
    files: globs.e2e,
    rules: {
      'playwright/consistent-spacing-between-blocks': 'warn',
      'playwright/expect-expect': 'error',
      'playwright/max-expects': 'off',
      'playwright/max-nested-describe': ['warn', { max: 5 }],
      'playwright/missing-playwright-await': 'error',
      'playwright/no-commented-out-tests': 'warn',
      'playwright/no-conditional-expect': 'warn',
      'playwright/no-conditional-in-test': 'warn',
      'playwright/no-duplicate-hooks': 'error',
      'playwright/no-duplicate-slow': 'off',
      'playwright/no-element-handle': 'warn',
      'playwright/no-eval': 'warn',
      'playwright/no-focused-test': 'warn',
      'playwright/no-force-option': 'warn',
      'playwright/no-get-by-title': 'off',
      'playwright/no-hooks': 'off',
      'playwright/no-nested-step': 'warn',
      'playwright/no-networkidle': 'warn',
      'playwright/no-nth-methods': 'off',
      'playwright/no-page-pause': 'warn',
      'playwright/no-raw-locators': 'off',
      'playwright/no-restricted-locators': 'off',
      'playwright/no-restricted-matchers': 'off',
      'playwright/no-restricted-roles': 'off',
      'playwright/no-skipped-test': 'warn',
      'playwright/no-slowed-test': 'warn',
      'playwright/no-standalone-expect': 'warn',
      'playwright/no-unsafe-references': 'warn',
      'playwright/no-unused-locators': 'warn',
      'playwright/no-useless-await': 'error',
      'playwright/no-useless-not': 'warn',
      'playwright/no-wait-for-navigation': 'warn',
      'playwright/no-wait-for-selector': 'warn',
      'playwright/no-wait-for-timeout': 'warn',
      'playwright/prefer-comparison-matcher': 'off',
      'playwright/prefer-equality-matcher': 'off',
      'playwright/prefer-hooks-in-order': 'off',
      'playwright/prefer-hooks-on-top': 'off',
      'playwright/prefer-locator': 'off',
      'playwright/prefer-lowercase-title': 'off',
      'playwright/prefer-native-locators': 'off',
      'playwright/prefer-strict-equal': 'off',
      'playwright/prefer-to-be': 'off',
      'playwright/prefer-to-contain': 'off',
      'playwright/prefer-to-have-count': 'off',
      'playwright/prefer-to-have-length': 'off',
      'playwright/prefer-web-first-assertions': 'warn',
      'playwright/require-hook': 'off',
      'playwright/require-soft-assertions': 'off',
      'playwright/require-tags': 'off',
      'playwright/require-to-pass-timeout': 'off',
      'playwright/require-to-throw-message': 'off',
      'playwright/require-top-level-describe': 'off',
      'playwright/valid-describe-callback': 'warn',
      'playwright/valid-expect-in-promise': 'warn',
      'playwright/valid-expect': 'warn',
      'playwright/valid-test-tags': 'off',
      'playwright/valid-title': 'warn',
    },
  };
}

export default playwright;
