import plugin from 'eslint-plugin-vitest';

import { globs } from '../utils/globs.mjs';

/**
 * @return { import('eslint').Linter.Config }
 */
function vitest() {
  return {
    files: globs.test,
    plugins: { vitest: plugin },
    languageOptions: {
      globals: {
        suite: 'writable',
        test: 'writable',
        describe: 'writable',
        it: 'writable',
        expect: 'writable',
        assert: 'writable',
        vitest: 'writable',
        vi: 'writable',
        beforeAll: 'writable',
        afterAll: 'writable',
        beforeEach: 'writable',
        afterEach: 'writable',
      },
    },
    rules: {
      'vitest/consistent-test-filename': 'off',
      'vitest/consistent-test-it': 'warn',
      'vitest/expect-expect': 'warn',
      'vitest/max-expects': 'off',
      'vitest/max-nested-describe': 'off',
      'vitest/no-alias-methods': 'off',
      'vitest/no-commented-out-tests': 'warn',
      'vitest/no-conditional-expect': 'warn',
      'vitest/no-conditional-in-test': 'off',
      'vitest/no-conditional-tests': 'warn',
      'vitest/no-disabled-tests': 'warn',
      'vitest/no-done-callback': 'off',
      'vitest/no-duplicate-hooks': 'error',
      'vitest/no-focused-tests': 'warn',
      'vitest/no-hooks': 'off',
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/no-interpolation-in-snapshots': 'warn',
      'vitest/no-large-snapshots': 'warn',
      'vitest/no-mocks-import': 'warn',
      'vitest/no-restricted-matchers': 'warn',
      'vitest/no-restricted-vi-methods': 'warn',
      'vitest/no-standalone-expect': 'warn',
      'vitest/no-test-prefixes': 'warn',
      'vitest/no-test-return-statement': 'warn',
      'vitest/prefer-called-with': 'warn',
      'vitest/prefer-comparison-matcher': 'warn',
      'vitest/prefer-each': 'warn',
      'vitest/prefer-equality-matcher': 'warn',
      'vitest/prefer-expect-assertions': 'off',
      'vitest/prefer-expect-resolves': 'warn',
      'vitest/prefer-hooks-in-order': 'warn',
      'vitest/prefer-hooks-on-top': 'warn',
      'vitest/prefer-lowercase-title': 'off',
      'vitest/prefer-mock-promise-shorthand': 'warn',
      'vitest/prefer-snapshot-hint': 'warn',
      'vitest/prefer-spy-on': 'warn',
      'vitest/prefer-strict-equal': 'off',
      'vitest/prefer-to-be': 'warn',
      'vitest/prefer-to-be-falsy': 'off',
      'vitest/prefer-to-be-object': 'warn',
      'vitest/prefer-to-be-truthy': 'off',
      'vitest/prefer-to-contain': 'warn',
      'vitest/prefer-to-have-length': 'warn',
      'vitest/prefer-todo': 'warn',
      'vitest/require-hook': 'warn',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'warn',
      'vitest/require-to-throw-message': 'warn',
      'vitest/require-top-level-describe': 'warn',
      'vitest/valid-describe-callback': 'warn',
      'vitest/valid-expect': 'warn',
      'vitest/valid-title': 'warn',
    },
  };
}

export default vitest;
