module.exports = {
  rules: {
    'class-methods-use-this': 'off',
    'no-class-assign': 'error',
    'no-duplicate-imports': 'off', // Handled by import plugin
    'no-restricted-imports': 'off',
    'no-return-await': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'warn',
    'prefer-const': 'warn',
    'prefer-exponentiation-operator': 'warn',
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-yield': 'error',
    'symbol-description': 'error',
    'constructor-super': 'error',
    'no-await-in-loop': 'error',
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-new-symbol': 'error',
    'no-this-before-super': 'error',
    'no-unused-expressions': 'off',
  },
};
