module.exports = {
  rules: {
    'arrow-body-style': ['off', 'as-needed'], // Annoying
    'brace-style': 'off', // prettier
    'camelcase': ['warn', { properties: 'always' }],
    'capitalized-comments': 'off',
    'comma-spacing': ['warn', { after: true, before: false }],
    'consistent-this': 'off',
    'func-name-matching': 'error',
    'func-names': 'error',
    'func-style': 'off',
    'id-denylist': 'off',
    'init-declarations': 'off',
    'id-length': 'off',
    'id-match': [
      'error',
      // __filename, camelCase, PascalCase, CONST_VALUE, stream$, $el
      '^\\$?(__)?(([A-Z]|[a-z]|[0-9]+)|([A-Z_]))*\\$?$',
    ],
    'linebreak-style': ['error', 'unix'],
    'line-comment-position': 'off',
    'lines-around-comment': 'off',
    'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: false }],
    'max-classes-per-file': 'off',
    'max-depth': ['error', 4],
    'max-lines': ['error', { max: 2500, skipBlankLines: false, skipComments: false }],
    'max-lines-per-function': ['error', 150],
    'max-nested-callbacks': ['error', 7],
    'max-params': ['error', 7],
    'max-statements-per-line': ['error', { max: 1 }],
    'max-statements': ['error', 40],
    'multiline-comment-style': 'off',
    'new-cap': 'off',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-multi-assign': 'error',
    'no-negated-condition': 'off',
    'no-nested-ternary': 'off',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-promise-executor-return': 'error',
    'no-ternary': 'off',
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'object-shorthand': ['error', 'properties'],
    'one-var': ['error', { uninitialized: 'never', initialized: 'never' }],
    'operator-assignment': 'off',
    'padding-line-between-statements': 'off',
    'prefer-arrow-callback': ['warn', { allowNamedFunctions: true, allowUnboundThis: true }],
    'prefer-destructuring': 'off',
    'prefer-object-spread': 'warn',
    'sort-keys': 'off',
    'sort-vars': 'off',
    'spaced-comment': ['warn', 'always', { markers: ['/'] }], // ignore typescript triple-slash
    'prettier/prettier': 'error',
  },
};
